[package]
name = "enc"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.50", features = ["derive"] }
colored = "3.0.0"
inquire = "0.9.1"
rusqlite = "0.37.0"
tabled = "0.20.0"
